
let allTypes = {
    USER_LOGIN:"USER_LOGIN",
    SIGNED_UP:"SIGNED_UP",
    INTERNET_ERROR:"INTERNET_ERROR",
    NOTIFICATION_MSG:"NOTIFICATION_MSG",
    SIGN_OUT:"SIGN_OUT",
    ADD_ITME_INTO_CART:"ADD_ITME_INTO_CART",
    REMOVE_ITME_FROM_CART:"REMOVE_ITME_FROM_CART",
    CART_LIST:"CART_LIST",
    REMOVE_ITME_FROM_CART:"REMOVE_ITME_FROM_CART",
    
}

export default allTypes